CONST_PREDICT_FILENAME = "training_set.csv"
CONST_PREDICT_INPUT_DIRECTORY = "./input"
CONST_TEST_SET_INPUT_DIRECTORY="test_data"
CONST_ALARM_SEQUENCE="AlarmSequence"
CONST_FREQUENCY="Frequency"
CONST_CLUSTER="Cluster"
CONST_SIMILARITY="Similarity"
CONST_ALARMTAG_INDEX=5
CONST_ALARMID_INDEX=6
CONST_STATUS_INDEX=11
CONST_CLUSTER_FIRST_COL=1
CONST_CLUSTER_SECOND_COL=2
CONST_CLUSTER_LENGTH=3
CONST_MOST_FREQUENT_SEQUENCE=10



#Constants used
CONST_TRAINING_SET ="training"
CONST_TEST_SET="test"

CONST_NAIVE_BAYES="NaiveBayes.R"
CONST_PREFILTER_FILENAME="Prefilter.R"
CONST_MSW_CLUSTER_FILENAME="MswAlgorithm.R"


# Algorithm Names
CONST_PREDICTION_ALOG ="prediction"
CONST_PREFILTER_ALGO="prefilter"
CONST_MSW_CLUSTER_ALSO="cluster"


# different path location of algorithms
CONST_PATH_LOC_PREDICTION="./rWorkspace/prediction"
CONST_PATH_LOC_PREFILTER="./rWorkspace/prefilter"
CONST_PATH_LOC_MSW_CLUSTER="./rWorkspace/msw_cluster"



